### ISSUE TITLE
Error creating backup: Null character in path.

### ISSUE THREAD

**Issue by akio4800** [NightmareXIV/JustBackup#24]
when you try to create a backup manually or automatic it fails with the message:
> [03.07.2024 22:16:52 +02:00] Error creating backup: Null character in path. (Parameter 'D:\Documents/My Games/FINAL FANTASY XIV - A Realm Reborn
> [03.07.2024 22:09:29 +02:00] Error deleting temp files: Could not find a part of the path 'C:\Users\<user>\AppData\Local\Temp\JustBackup-1720037369708'.
   at System.IO.FileSystem.GetFindData(String fullPath, Boolean isDirectory, Boolean ignoreAccessDenied, WIN32_FIND_DATA& findData)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at JustBackup.JustBackup.<>c__DisplayClass12_0.<DoBackupInternal>b__0() in /work/repo/JustBackup/JustBackup.cs:line 333

Documents is on second drive

**Comment by Limiana** [comment]
Thank you for the report! A fix is already released and sent for approval, once version 1.1.0.8 please test it and report if the problem is gone

**Comment by pkrainer** [comment]
thank you for fixing it !

**Comment by akio4800** [comment]
thank you for fixing it
