### ISSUE TITLE
Error creating backup: Access to the path denied

### ISSUE THREAD

**Issue by VeronicVR** [NightmareXIV/JustBackup#25]
Seems to not be able to access some Browsingway config files. 

```
> [7/5/2024 8:37:02 AM -07:00] Error creating backup: Access to the path 'C:\Users\Veronic\AppData\Roaming\XIVLauncher\pluginConfigs\Browsingway\cef-cache\AutofillStates\2024.6.5.140657' is denied.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at JustBackup.JustBackup.CloneDirectory(String root, String dest, Boolean all, String[] Exclusions) in /work/repo/JustBackup/JustBackup.cs:line 361
   at JustBackup.JustBackup.CloneDirectory(String root, String dest, Boolean all, String[] Exclusions) in /work/repo/JustBackup/JustBackup.cs:line 373
   at JustBackup.JustBackup.CloneDirectory(String root, String dest, Boolean all, String[] Exclusions) in /work/repo/JustBackup/JustBackup.cs:line 373
   at JustBackup.JustBackup.CloneDirectory(String root, String dest, Boolean all, String[] Exclusions) in /work/repo/JustBackup/JustBackup.cs:line 373
   at JustBackup.JustBackup.CloneDirectory(String root, String dest, Boolean all, String[] Exclusions) in /work/repo/JustBackup/JustBackup.cs:line 373
   at JustBackup.JustBackup.<>c__DisplayClass12_0.<DoBackupInternal>b__0() in /work/repo/JustBackup/JustBackup.cs:line 170
```

**Comment by Limiana** [comment]
Hello! This is simply a cache file that is failing to be copied. This error can be safely ignored and it's probably good to add this path to exclusions

**Comment by VeronicVR** [comment]
Gotcha! Thanks for this info! Fixed.
