### ISSUE TITLE
Error copying plugin configs

### ISSUE THREAD

**Issue by Lavitz118** [NightmareXIV/JustBackup#27]
I am receiving the follow error for all 5 currently installed plugins. Occurs at automated startup backup and manual backup.

[Error@9/10/2024 12:13:42 AM -05:00] Error copying file C:\Users\<username>\AppData\Roaming\XIVLauncher\pluginConfigs\ChatBubbles.json to Z:\Final Fantasy\FF14\Backups\Temps\JustBackup-1725945222731\plugins: Could not find a part of the path 'Z:\Final Fantasy\FF14\Backups\Temps\JustBackup-1725945222731\plugins\ChatBubbles.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at JustBackup.JustBackup.CopyFile(String file, String dest) in /work/repo/JustBackup/JustBackup.cs:line 394

**Comment by OrphieBaby** [comment]
Same issue
